[
    uuid(8f5a6d4e-4438-4f3f-a12c-621947978a21),
    version(1.0),
    implicit_handle(handle_t TrayServiceRpcBinding),
    pointer_default(unique)
]
interface TrayServiceRpc
{
    void RpcStopTrayService();
}
